### ISSUE TITLE
O3DE Friendly Names for Releases

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-release#20]
**Problem:** 
While specific release numbers are precise, they sometimes aren't friendly for discussion/communication.
(JoeB: I am expanding this issue to cover naming going forward, not just the 2111 build that has already released)
**Suggestion:** 
O3DE names its releases with friendly names in addition to the underlying numeric release.

**This issue should be considered "done" when:** 
1) it's decided if O3DE will have friendly names
2) a theme is decided on
3) a format for the friendly name is decided on

Please propose any themes and formats as comments to this issue. We will take these comments, vote on the suggestions, then take the top voted suggestions to the marketing committee and the tech steering committee.

Requirements for suggestions:
1) Theme needs to have longevity, covering at least 50+ major releases
2) Theme needs to not infringe on any trademarked or copyrighted material
3) Theme should be inoffensive enough to be mass marketable (reviews, publications, ads, news coverage, etc). 
4) Theme must adhere to O3DE and Linux Foundation code of conduct standards as posted here https://lfprojects.org/policies/code-of-conduct/
5) Theme should not be some variation of the release versioning (example 21.11). Incorporating the release version into the friendly name can cause confusion when communicating the friendly name vs the version to the public.

**Comment by AMZN-Liv** [comment]
I like this idea and think it will take some time for us to get alignment around a theme, but it's a good goal for us to have going into 2022.

**Comment by ppinfel** [comment]
is there example like how it will work will 21.11.1 vs 21.11.2 have different name?

**Comment by Sanbiz** [comment]
I like the idea of naming for major releases but not minor/point releases, which is similar to how other projects use naming. Naming for point releases could add confusion and there's an expectation that any contributor/customer would pull the latest revision of any major release.

**Comment by amzn-leenguy** [comment]
> 

Would be cool to pay homage to our previous Mascot theLumberyard Beaver, we should name our releases after different types of Wood. Doing a quick google search i can see:

Cedar
Pine
Redwood
Aspen
Boxwood
Cherry
Coachwood
Eucalyptus
Hickory
Locus
Olive
Bamboo

**Comment by amznestebanpapp** [comment]
I will ask to be mindful of developers/engineers. I would like to see more voices and opinions from contributors on this.

My take is that this introduces yet another mapping to do in order to find where to find/fix things or what someone is talking about. 
Since issues are usually reported in written, and reporters may not have access to labels, this makes it prone for someone to report it to that name instead of a specific version number. E.g someone reporting an issue against "Cedar" instead of "21.11.1". 

Usually these names are introduced and then assumed that engineering will adopt/know them, and that is rarely the case because they are not practical for the workflows that developers/engineers use. As an example, note that we never refer to the Ubuntu versions as their friendly names, not for our requirements not for explanations/chats. E.g. we refer to "Ubuntu 20.04 LTS", not to "Ubuntu Focal Fossa". If someone were to tell me that O3DE doesn't work on "Ubuntu Bionic Beaver" I have to convert that "Bionic Beaver" to "18.04" which is the information I need to map it to the issue why we don't support it.

Friendly names make it harder to fix issues... it gets harder to understand what branch it corresponds to, what issues were merged to it, what point in time and what ordering it has (i.e. which was the previous and next versions). All those things are needed in order to debug issues (e.g. comparing with previous version is sometimes needed), place the fix in the right version and propagate it to the following versions. 

For internal development, using names is not practical. Scripts and rules need to be made in order to detect these special branches (e.g. to setup specific Jenkins jobs in them), 
For an engineer its easier to understand that an issue reported against 1.1.1 needs to be fixed in the 1.1 branch (so the next release gets it); needs to be propagated to the 1.X branches (where X > 1); propagated to Y.X where Y > 1; and propagated to the development branch. 
For scripts its easier to write rules that branches called `stabilization\/[0-9]*$` needs nightly jobs. 

I am concerned about someone stating something like "the issue happened in Cedar", which should match to 21.11.X, but we have 21.11.1 and 21.11.2, and the internal name of that branch is 2110, but the .2 of it is 2111RTE. All that mapping is not day-to-day to developers so it is prone to errors and time waste.

**Comment by erickson-doug** [comment]
Consider SEO when proposing a friendly name model.

**Comment by sptramer** [comment]
Agreed with Doug. This is the reason why you tend to have the "Alliterative Adjective Animal" naming schemes (Bionic Beaver, Focal Fossa, etc.) You want the word pairing to be unique enough that it's easy to search for and easy to remember. Wood/trees are actually a good one since they can both be an adjective (describing a physical object made of the wood) or an animal (the tree.)

**Comment by amzn-leenguy** [comment]
> Agreed with Doug. This is the reason why you tend to have the "Alliterative Adjective Animal" naming schemes (Bionic Beaver, Focal Fossa, etc.) You want the word pairing to be unique enough that it's easy to search for and easy to remember. Wood/trees are actually a good starting point since they can both be an adjective (describing a physical object made of the wood) or an animal (the tree.)

I love this idea of mixing two words. !
