### ISSUE TITLE
22.05.0 Known Issues List

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-release#55]
Please add a comment to this issue with any known issues you would like called out for the 22.05.0 list which is here: https://github.com/o3de/sig-release/blob/main/releases/22.05.0/O3DE%2022050%20Release%20Notes.md

**Comment by galibzon** [comment]
https://github.com/o3de/o3de/issues/9157

I will submit a release note.

**Comment by lmbr-pip** [comment]
For sig-content/asset pipeline from previous notes:

* The O3DE Editor may crash if launched before project assets have been processed and PhysX tab in FBX Settings is used. This is due to the global physics material library asset being not ready to be used. (_Could not find issue for this so assume still valid_ @hultonha any ideas)?
To work around this issue, run AssetProcessor to process project assets before launching Editor for the first time. After all assets are processed initially, Editor can be launched without manually running AssetProcessor.

* Linux only: Closing Editor while Asset Processor is still running will result in a crash upon relaunching the Editor. ((_Could not find issue for this so assume still valid_)

These were resolved and should be removed.
* ~~MaterialType Default Values Not Initially Applied error. When changing a default material property value, materials may continue using the prior default value.GitHub Issue: [o3de/o3de#5213](https://github.com/o3de/o3de/issues/5213)~~
* ~~MaterialType New Property Not Initially Applied error. When adding new material properties, the Asset Processor may initially fail for material files, and the AP needs a re-scan or restart.GitHub Issue: [o3de/o3de#5215](https://github.com/o3de/o3de/issues/5215)~~

**Comment by lmbr-pip** [comment]
For sig-network, from previous notes:

* Network entity hierarchies are limited to hierarchies with max count of 16 entities.
* GameLift server launchers are manually relocatable. There is currently no automated build or asset layout generation. See instructions here: AWS GameLift Gem Build Packaging for Windows and AWS GameLift Gem Build Packaging for Linux . (You can ignore GameLift-specific steps if you are not relocating your servers to GameLift instances).
* Monolithic release server builds are currently not supported.
* imgui keyboard is not working in server launcher.
* console is not working on server launcher.

New known issues:
* If you experience unexpected client disconnect issues with Multiplayer, set `sv_isTransient=False` to see if server auto termination logic is causing issue . See https://www.o3de.org/docs/user-guide/networking/settings/ for further settings.
* All CDK samples in the AWS Gems are for CDK v1 (https://docs.aws.amazon.com/cdk/v1/guide/home.html). CDK applications are not currently compatible with CDK v2.

**Comment by hultonha** [comment]
>

**Comment by hultonha** [comment]
Responding to @lmbr-pip about this issue

> The O3DE Editor may crash if launched before project assets have been processed and PhysX tab in FBX Settings is used. This is due to the global physics material library asset being not ready to be used. (Could not find issue for this so assume still valid @hultonha any ideas)?
To work around this issue, run AssetProcessor to process project assets before launching Editor for the first time. After all assets are processed initially, Editor can be launched without manually running AssetProcessor.

This was fixed here - https://github.com/o3de/o3de/issues/6027

**Comment by Ulrick28** [comment]
I have added everything listed here to the release, except the items deemed resolved for this release.

**Comment by Ulrick28** [comment]
Closing as this list is now a part of the release notes.
